from enum import auto
from occurence import *


def filter_out(dic, threshold):
    """
    returns the dictionnary generated by file_extractor but filtered
    """
    return dict(filter(lambda occurence: int(occurence[1]) > threshold, dic.items()))


def find_sequence_in_reads(file_path, mutation):
    """
    aims to find from which read the k-mer mutation is extracted
    """
    dic = defaultdict(int)
    #we parse the .fna file
    records = list(Bio.SeqIO.parse(file_path,"fasta"))
    for record in records[:int(len(records))]:
        #for each sample we extract the nucleotide sequence in the SEQ variable
        SEQ = str(record.seq)
        if SEQ.find(mutation) != -1:
            dic[SEQ] += 1
    return dic




