from occurence import dictionnary_writer

file_path_initial = "outputs/dic_initial.txt"
file_path_variant = "outputs/dic_variant.txt"
output_file_path_initial = "outputs/dic_initial_filtered.txt"
output_file_path_variant = "outputs/dic_variant_filtered.txt"


def file_extractor(file_path):
    """
    returns a dictionary which is the same than the one created in occurence.py
    """
    d = {}
    with open(file_path, "r") as f:
        for line in f.readlines():
            S = line.split()
            d[S[0]] = int(S[1])
    return d


threshold = 1


def filter_out(dic, threshold):
    """
    returns the dictionary generated by file_extractor but filtered
    """
    new_dic = dict(filter(lambda occurence: int(occurence[1]) > threshold, dic.items()))
    return new_dic


if __name__ == "__main__":
    D = file_extractor(file_path_initial)
    filtered_dic = filter_out(D, threshold)
    #as previously we write our filtered result in a file to eventually
    #process it later
    dictionnary_writer(filtered_dic, output_file_path_initial)

    D = file_extractor(file_path_variant)
    filtered_dic = filter_out(D, threshold)
    #as previously we write our filtered result in a file to eventually
    #process it later
    dictionnary_writer(filtered_dic, output_file_path_variant)
